name: WD Capstone test
"on": push
env:
  PG_DATABASE: wd-election-test
  PG_USER: postgres
  PG_PASSWORD: 12345678
jobs:
  run-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: "postgres:11.7"
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 12345678
          POSTGRES_DB: wd-election-test
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5
        ports:
          - "5432:5432"
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run build
        run: npm run build
      - name: Code Validation
        run: npm run lint
      - name: Run unit tests
        run: npm test
      - name: Run the app
        id: run-app
        run: |
          npm install
          npx sequelize-cli db:drop
          npx sequelize-cli db:create
          npx sequelize-cli db:migrate
          PORT=5001 npm start &
          sleep 5
      - name: Run integration tests
        run: |
          npm install cypress cypress-json-results
          npx cypress run
  deploy:
    - name: Deploy
      needs:
        - run-tests
      runs-on: ubuntu-latest
      steps:
        - name: Deploy to production
          uses: johnbeynon/render-deploy-action@v0.0.8
          with:
            service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
            api-key: ${{ secrets.MY_RENDER_API_KEY }}
